services:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_manager/alerts.yml:/etc/prometheus/alerts.yml
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana  # Set admin password
      - GF_USERS_ALLOW_SIGN_UP=false  # Disable sign-up for users
      - TZ=${SYSTEM_TIMEZONE:-Europe/Moscow}
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    deploy:
      placement:
        constraints: [node.role == manager]

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    deploy:
      mode: global

  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - monitoring
    deploy:
      mode: global


  blackbox_exporter: # HTTP, HTTPS, DNS, TCP, ICMP monitoring
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    networks:
      - monitoring


  cadvisor:  # analyzes and exposes resource usage and performance data from running containers.
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    deploy:
      mode: global
    networks:
      - monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alert_manager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    networks:
      - monitoring
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  monitoring:
    external: true
    name: monitoring

volumes:
  grafana-storage:
